/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class UpdateEventDetails!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGUpdateEventDetailsBase.h"
#include "OSGUpdateEventDetails.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::UpdateEventDetails
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Time            UpdateEventDetailsBase::_sfElapsedTime
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<UpdateEventDetails *, nsOSG>::_type(
    "UpdateEventDetailsPtr", 
    "InputEventDetailsPtr", 
    UpdateEventDetails::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(UpdateEventDetails *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           UpdateEventDetails *,
                           nsOSG);


/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void UpdateEventDetailsBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFTime::Description(
        SFTime::getClassType(),
        "ElapsedTime",
        "",
        ElapsedTimeFieldId, ElapsedTimeFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&UpdateEventDetails::editHandleElapsedTime),
        static_cast<FieldGetMethodSig >(&UpdateEventDetails::getHandleElapsedTime));

    oType.addInitialDesc(pDesc);
}


UpdateEventDetailsBase::TypeObject UpdateEventDetailsBase::_type(
    UpdateEventDetailsBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&UpdateEventDetailsBase::createEmptyLocal),
    UpdateEventDetails::initMethod,
    UpdateEventDetails::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&UpdateEventDetails::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"UpdateEventDetails\"\n"
    "    parent=\"InputEventDetails\"\n"
    "    library=\"Base\"\n"
    "    pointerfieldtypes=\"single\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    supportUnregisteredCreate=\"true\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "    <Field\n"
    "        name=\"ElapsedTime\"\n"
    "        type=\"Time\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"protected\"\n"
    "        defaultValue=\"0.0\"\n"
    "        publicRead=\"true\"\n"
    "    >\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &UpdateEventDetailsBase::getType(void)
{
    return _type;
}

const FieldContainerType &UpdateEventDetailsBase::getType(void) const
{
    return _type;
}

UInt32 UpdateEventDetailsBase::getContainerSize(void) const
{
    return sizeof(UpdateEventDetails);
}

/*------------------------- decorator get ------------------------------*/


SFTime *UpdateEventDetailsBase::editSFElapsedTime(void)
{
    editSField(ElapsedTimeFieldMask);

    return &_sfElapsedTime;
}

const SFTime *UpdateEventDetailsBase::getSFElapsedTime(void) const
{
    return &_sfElapsedTime;
}






/*------------------------------ access -----------------------------------*/

UInt32 UpdateEventDetailsBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ElapsedTimeFieldMask & whichField))
    {
        returnValue += _sfElapsedTime.getBinSize();
    }

    return returnValue;
}

void UpdateEventDetailsBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ElapsedTimeFieldMask & whichField))
    {
        _sfElapsedTime.copyToBin(pMem);
    }
}

void UpdateEventDetailsBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ElapsedTimeFieldMask & whichField))
    {
        editSField(ElapsedTimeFieldMask);
        _sfElapsedTime.copyFromBin(pMem);
    }
}

//! create a new instance of the class
UpdateEventDetailsTransitPtr UpdateEventDetailsBase::createLocal(BitVector bFlags)
{
    UpdateEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<UpdateEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
UpdateEventDetailsTransitPtr UpdateEventDetailsBase::createDependent(BitVector bFlags)
{
    UpdateEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<UpdateEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
UpdateEventDetailsTransitPtr UpdateEventDetailsBase::create(void)
{
    UpdateEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<UpdateEventDetails>(tmpPtr);
    }

    return fc;
}

UpdateEventDetails *UpdateEventDetailsBase::createEmptyLocal(BitVector bFlags)
{
    UpdateEventDetails *returnValue;

    newPtr<UpdateEventDetails>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
UpdateEventDetails *UpdateEventDetailsBase::createEmpty(void)
{
    UpdateEventDetails *returnValue;

    newPtr<UpdateEventDetails>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

UpdateEventDetails *UpdateEventDetailsBase::createUnregistered(void)
{
    UpdateEventDetails *returnValue = new UpdateEventDetails;

#ifdef OSG_MT_CPTR_ASPECT
    returnValue->setupAspectStore();
#endif
    //Do not register with the FieldContainer Factory

    returnValue->onCreate      (      );
    returnValue->onCreateAspect(returnValue);
    
    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();
    
    return returnValue;
}

FieldContainerTransitPtr UpdateEventDetailsBase::shallowCopyLocal(
    BitVector bFlags) const
{
    UpdateEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const UpdateEventDetails *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr UpdateEventDetailsBase::shallowCopyDependent(
    BitVector bFlags) const
{
    UpdateEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const UpdateEventDetails *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr UpdateEventDetailsBase::shallowCopy(void) const
{
    UpdateEventDetails *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const UpdateEventDetails *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

UpdateEventDetailsBase::UpdateEventDetailsBase(void) :
    Inherited(),
    _sfElapsedTime            (Time(0.0))
{
}

UpdateEventDetailsBase::UpdateEventDetailsBase(const UpdateEventDetailsBase &source) :
    Inherited(source),
    _sfElapsedTime            (source._sfElapsedTime            )
{
}


/*-------------------------- destructors ----------------------------------*/

UpdateEventDetailsBase::~UpdateEventDetailsBase(void)
{
}


GetFieldHandlePtr UpdateEventDetailsBase::getHandleElapsedTime     (void) const
{
    SFTime::GetHandlePtr returnValue(
        new  SFTime::GetHandle(
             &_sfElapsedTime,
             this->getType().getFieldDesc(ElapsedTimeFieldId),
             const_cast<UpdateEventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr UpdateEventDetailsBase::editHandleElapsedTime    (void)
{
    SFTime::EditHandlePtr returnValue(
        new  SFTime::EditHandle(
             &_sfElapsedTime,
             this->getType().getFieldDesc(ElapsedTimeFieldId),
             this));


    editSField(ElapsedTimeFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void UpdateEventDetailsBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    UpdateEventDetails *pThis = static_cast<UpdateEventDetails *>(this);

    pThis->execSync(static_cast<UpdateEventDetails *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *UpdateEventDetailsBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    UpdateEventDetails *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const UpdateEventDetails *>(pRefAspect),
                  dynamic_cast<const UpdateEventDetails *>(this));

    return returnValue;
}
#endif

void UpdateEventDetailsBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
