/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGUPDATEEVENTDETAILSFIELDS_H_
#define _OSGUPDATEEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class UpdateEventDetails;

OSG_GEN_CONTAINERPTR(UpdateEventDetails);
/*! \ingroup GrpBaseFieldTraits
    \ingroup GrpLibOSGBase
 */
template <>
struct FieldTraits<UpdateEventDetails *, nsOSG> :
    public FieldTraitsFCPtrBase<UpdateEventDetails *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<UpdateEventDetails *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_BASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

};

template<> inline
const Char8 *FieldTraits<UpdateEventDetails *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecUpdateEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<UpdateEventDetails *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecUpdateEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<UpdateEventDetails *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakUpdateEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<UpdateEventDetails *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdUpdateEventDetailsPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<UpdateEventDetails *,
                      RecordedRefCountPolicy, nsOSG  > SFRecUpdateEventDetailsPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<UpdateEventDetails *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecUpdateEventDetailsPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<UpdateEventDetails *,
                      WeakRefCountPolicy, nsOSG      > SFWeakUpdateEventDetailsPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<UpdateEventDetails *,
                      NoRefCountPolicy, nsOSG        > SFUncountedUpdateEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFRecUpdateEventDetailsPtr : 
    public PointerSField<UpdateEventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFUnrecUpdateEventDetailsPtr : 
    public PointerSField<UpdateEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFWeakUpdateEventDetailsPtr :
    public PointerSField<UpdateEventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFUncountedUpdateEventDetailsPtr :
    public PointerSField<UpdateEventDetails *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGUPDATEEVENTDETAILSFIELDS_H_ */
