/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGKEYEVENTDETAILSFIELDS_H_
#define _OSGKEYEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class KeyEventDetails;

OSG_GEN_CONTAINERPTR(KeyEventDetails);
/*! \ingroup GrpSystemFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<KeyEventDetails *, nsOSG> :
    public FieldTraitsFCPtrBase<KeyEventDetails *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<KeyEventDetails *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

};

template<> inline
const Char8 *FieldTraits<KeyEventDetails *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecKeyEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyEventDetails *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecKeyEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyEventDetails *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakKeyEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyEventDetails *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdKeyEventDetailsPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<KeyEventDetails *,
                      RecordedRefCountPolicy, nsOSG  > SFRecKeyEventDetailsPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<KeyEventDetails *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecKeyEventDetailsPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<KeyEventDetails *,
                      WeakRefCountPolicy, nsOSG      > SFWeakKeyEventDetailsPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<KeyEventDetails *,
                      NoRefCountPolicy, nsOSG        > SFUncountedKeyEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecKeyEventDetailsPtr : 
    public PointerSField<KeyEventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecKeyEventDetailsPtr : 
    public PointerSField<KeyEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakKeyEventDetailsPtr :
    public PointerSField<KeyEventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedKeyEventDetailsPtr :
    public PointerSField<KeyEventDetails *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGKEYEVENTDETAILSFIELDS_H_ */
